name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_HOME: ${{ github.workspace }}/.cargohome
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ${{ env.CARGO_HOME }}/registry/index/
            ${{ env.CARGO_HOME }}/registry/cache/
            ${{ env.CARGO_HOME }}/git/db/
      - name: Build
        run: cargo build --workspace
      - name: Run tests
        run: cargo test --workspace
      - name: Build rocket_tls_compat_check
        run: cd rocket_tls_compat_check && cargo build --workspace
